### PR TITLE
Removing deprecated services and child/ancestor methods

### LINKED ISSUE #138: 07-31-2015 Remove deprecated methods associated with PR 136
Search for DEPRECATION and remove any deprecated methods with a target date of 07-31-2015 or earlier.

### PR DESCRIPTION
**Pull request by escowles**
Fixes #138

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Can you also remove outdated `autoload` entries from `lib/hydra/pcdm.rb`?

**Comment by escowles** [comment]
@mjgiarlo, I've updated the PR to remove the ChildObjects autoload.

**Comment by terrellt** [comment]
@escowles I think he meant things like https://github.com/escowles/hydra-pcdm/blob/remove-deprecated-services/lib/hydra/pcdm.rb#L32-L41

**Comment by escowles** [comment]
Thanks @terrellt -- I've removed those now.

**Comment by terrellt** [comment]
I'm :+1: - you good @mjgiarlo ?

**Comment by mjgiarlo** [comment]
:+1: :shipit:

**Pull request merged**
