### PR TITLE
Remove the append (<<) operator from Collection and Object

### PR DESCRIPTION
**Pull request by jcoyne**
This is an alternative to #84

### CODE REVIEW

**Comment by elrayle** [comment]
I am fine with merging this.  Do we want to have an alternative allowing for append?

Options:
```
 coll1.collections << coll2  # desired but complex since collections is a method and not a ruby object
coll1.collections = coll1.collections + coll2   # inefficient as all proxies are deleted and recreated
AddCollectionToCollection( parent_coll, child_coll )   parent_coll.members << child_coll  # service object
```

**Comment by elrayle** [comment]
One other thought, since members already supports <<, should it be overridden to validate the thing being appended is of the correct type?

**Comment by jcoyne** [comment]
@elrayle it's fine if you want to validate members, but I don't know how that pertains to this commit. Should that be a new issue?

**Comment by elrayle** [comment]
The validation process has been moved to services.  See PR https://github.com/projecthydra-labs/hydra-pcdm/pull/93.

Is there any code making use of the << operator and needs to be modified prior to a merge?

**Pull request merged**
