### PR TITLE
Fixing a few rubocop wording changes

### PR DESCRIPTION
**Pull request by njaffer**
Deleted contains def

Deleted deprecated methods

Deleted pcdm spec file

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@njaffer I get the rubocop changes by why are we deleting the model validations and validation specs?  Sorry if that's something I missed while away!

**Comment by njaffer** [comment]
I combined the two issues , the contains= removal, and also removing the deprecated function self.collection and self.object. When I removed those functions the spec were failing so when I deleted the spec file, the tests passed. I am not sure if that was the right think to do or not?
 
Thanks,
Nabeela

**Comment by mjgiarlo** [comment]
@terrellt @escowles @grosscol Are we looking to do away with the model validations in hydra-pcdm? @njaffer I wasn't sure if there was an issue already asking for that change -- I may have just missed it (being on vacation, I'm operating with less context than usual but I wanted to comment on this PR since it looked like it was waiting for some attention).

In the meantime, could you rebase on master and maybe bring this issue up on tomorrow's standup to make sure it can be merged in a timely fashion.

**Comment by escowles** [comment]
Yes, I think we should remove the package-level model validations -- these are replaced by each class defining its own validations, e.g.: https://github.com/projecthydra-labs/hydra-pcdm/blob/master/lib/hydra/pcdm/models/concerns/collection_behavior.rb#L32

**Comment by mjgiarlo** [comment]
:ok:  Thanks, @escowles

**Comment by mjgiarlo** [comment]
@njaffer We can merge this as soon as you rebase on the latest commits in master and squash your commits. Thanks again.

**Pull request closed without merging**
