### PR TITLE
Removing memoized object as query is stateless

### PR DESCRIPTION
**Pull request by jeremyf**
## Removing memoized object as query is stateless

@7fd3cf9155d3707aaec48f14cefed6ddd02c37e7

There was not a benefit to memoizing the AncestorChecker object. So I
opted to remove the memoization and favor a module function.

I also did some parameter renaming to reflect that the parameter names
switched meaning across the call into the AncestorChecker.

And finally added a missing spec for potential deep ancestry.

## Replacing unnecessary object creation

@f2c5c7af9c2a2032b30ab3b06c56964acccd6c93

In looking at the gemspec requirements, I see that Hydra::PCDM is for
ruby 1.9.3 or greater. This means no keyword args. So instead of using
the shim of hash keys, I've replaced them with positional args. This
reduces the number of hashes created on the method call.

I have also replaced the DeepMemberIterator logic with a recursive
method call. Consider the two scenarios, one using DeepMemberIterator
and the other using method calls and some duck typing:

```ruby
record.members == [a, b, c]
a.members == [d, e, f, g]
b.members == [h, i]
c.members == [j, k]
k.members == [l, m, n, o, p]
```

When DeepMemberIterator is used in the above scenario, we will
instantiate approximately:

* 17 instances of Hydra::PCDM::HasMembers
* 17 instances of Hydra::PCDM::DeepMemberIterator
* And loop twice through each of `[a,b,c]`, `[d, e, f, g]`, `[h, i]`,
  `[j, k]`, and `[l, m, n, o, p]`

## Removing DeepMemberIterator

@aba866c1b5f73dc52fc62ee44b577859b179843b

Based on the previous commit, the DeepMemberIterator is not needed.
I checked through the two organizations (i.e. projectyhdra and
projecthydra-labs) for any additional uses of DeepMemberIterator, and
found none.

Perhaps this should be deprecated instead. I don't know if the class is
part of the public api or not.

(If it isn't perhaps we should mark the constant as a private constant
or document it as @api private)?

## Renaming opaque `.call` method

@d7501e94044210feb1f69c62565b794a6babddf4

When I was orienting to the code, it took a bit to understand the
ancestor? method ordering and purpose. As I was extracting a module
function, I opted to go with `.call`. However, when I went back to the
method, I had to once again reorient to what was going on.

So I opted for the new method name `.former_is_ancestor_of_latter?`.
This resulted in a change in parameter order. To preserve parameter
order, I considered the method `.latter_is_ancestor_of_former?` but
that was more difficult to parse when reading.

### CODE REVIEW

**Comment by jeremyf** [comment]
As is policy: Don't merge this as there are three distinct commits that should have discussion.

**Comment by jcoyne** [comment]
It looks okay to me. I'd like @tpendragon to bless this as he wrote some of the code you're removing.

**Comment by tpendragon** [comment]
Looking at this now.

**Comment by tpendragon** [comment]
All three look like reasonable commits to me. I'm never a big fan of the `#call` interface, but as it's hidden behind the ancestors method, which is where the public things happen anyways, I'm less concerned.

Thanks for all your work on hydra-pcdm lately by the way, @jeremyf

**Comment by jeremyf** [comment]
@tpendragon I'm up for renaming the method from `.call` to something else.

**Comment by jeremyf** [comment]
@tpendragon And its been a long-time coming. I'm working at digging out of burnout, over-commitment, and team changes at ND. So I decided why not use my evening and day off to contribute to a community that I love.

**Comment by tpendragon** [comment]
@jeremyf We all appreciate your expertise. :)

Renaming the method won't change anything here, so it's fine. I struggle with what a more OO thing would be in cases like this, while still holding to SRP. Maybe the trick is an `Ancestors` object, with an `#include?` method, but meh.

**Comment by jeremyf** [comment]
@tpendragon I'm actually going to rename the method. Because I found it confusing when I was looking at the code. I'm checking that the given potential ancestor is or is not an ancestor of the given record.

**Comment by tpendragon** [comment]
I'm :+1:, and pretty ambivalent about parameter order for what's effectively a private interface.

As an aside, we should probably stop supporting 1.9.3.

Any more comments, @jcoyne?

**Pull request merged**
