### PR TITLE
Add related_files to Object. Fixes #62

### LINKED ISSUE #62: Objects can have related files

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by terrellt** [comment]
@jcoyne I thought the agreement in a previous call was to push off "related files" until after the sprint, and just deal with the "related objects (ore::aggregates)" concept.

Largely because of the concern that relating a "relatedFile" to an object isn't accurate, and it should rather just be linked directly to the file it's about.

**Comment by jcoyne** [comment]
@terrellt Hmm, that's the first I heard of this.

**Comment by flyingzumwalt** [comment]
@jcoyne we decided last week that it can be left out of scope or made very low priority because there are no diagrams that actually show it being used.  It certainly doesn't impact Sufia (which is driving this sprint)

**Comment by jcoyne** [comment]
Won't fix. See #184

**Pull request closed without merging**
