### PR TITLE
Add Object#child_object_ids

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
:+1:

**Comment by scherztc** [comment]
Code reading up on indexers, child_objects, and pcdm.  

When I ran the test locally I got a Syntax error in:

/hydra-pcdm/spec/hydra/pcdm/models/collection_spec.rb:73: syntax error, unexpected ')' (SyntaxError)

Are these test meant to only run on travis?

**Comment by jcoyne** [comment]
@scherztc the tests should run the same anywhere. They work on my machine and on Travis. Are you sure you have a clean checkout?

**Comment by scherztc** [comment]
Fresh clone, clean checkout, bundle update, rake spec,....

Still getting error.  I am on ruby-2.0.0-p247. 

Same method in either object_spec or collection_spec.

def build_proxy(container:)
      instance_double(ActiveFedora::Aggregation::Proxy, container: container)
end

ruby version?

**Comment by jcoyne** [comment]
have you tried `bundle exec rspec` ?  I'm using ruby 2.2.2.

**Comment by scherztc** [comment]
yes.  I will try an updated ruby version.

**Comment by jcoyne** [comment]
Oh, yeah, that code has required keyword arguments which is a ruby 2.1 feature. Blame @terrellt :exclamation:

**Comment by scherztc** [comment]
All test passing locally with ruby 2.1.5.  I will merge.

**Pull request merged**
