### PR TITLE
add and test service: CreateCollection

### PR DESCRIPTION
**Pull request by elrayle**

### CODE REVIEW

**Comment by terrellt** [comment]
What's the intended use? For end users?

This is a pretty rare case right? Wanting to create a collection without first associating metadata with it.

**Comment by elrayle** [comment]
See discussion of service objects at [Value of a Service Object Approach](https://wiki.duraspace.org/x/UgMdB)

**Comment by jcoyne** [comment]
@elrayle But still, it should accept and set attributes on the object. It can check that the member_ids attribute doesn't contain any illegal (File) ids.

**Comment by terrellt** [comment]
I guess my concern is that this service object is a Factory which can only create pre-persisted objects. I'm hesitant to add encapsulation that isn't used, and will have to be actively avoided.

**Comment by jcoyne** [comment]
@terrellt elaborate on that. You're thinking it should just give you a new object?

**Comment by terrellt** [comment]
@jcoyne Yeah. Encapsulate what it takes to create a Collection so that you can modify what gets returned without modifying the class' responsibility.

@elrayle Open/Closed Principle says that classes are closed to modification, but open for extension. This service object has no extension points, meaning that it's only purpose can ever be Collection.create, which doesn't add anything of value. If you allow for a factory to be injected into it, then you can abstract what it takes to create something, but I think that abstraction is built into the API already.

**Comment by elrayle** [comment]
Please see [Discusson](https://wiki.duraspace.org/display/hydra/Service+Object+Approach#ServiceObjectApproach-Discussion) section.  It describes two issues raised by Hector and Trey and provides pseudo code demonstrating extending models and example use of service objects.  This is of interest to both sub-components and Sufia sprint teams.

**Comment by elrayle** [comment]
I added an example of a complex service object class to the wiki doc at [Pseudocode of a complex service object class](https://wiki.duraspace.org/display/hydra/Service+Object+Approach#ServiceObjectApproach-Pseudocodeofacomplexserviceobjectclass).  This demonstrates a Sufia defined service object doing Sufia specific tasks and then calling Works level service objects for basic tasks.

**Comment by elrayle** [comment]
@terrellt Would you be opposed to merging this PR, with the understanding that it may need to change or be removed depending on the resolution to your concern.  To summarize your concern so I make sure I understand it correctly:
* DESIRED:  get an instance of ActiveFedora::Base, set all values, and then persist into Fedora (only 1 call to Fedora)  
* UNDESIRED:  use ActiveFedora:Base create method, which immediately creates the collection in Fedora, then set the values, and save again to update.  (2 calls to Fedora)

This appears to be a question of performance, making 1 vs. 2 calls into Fedora for each create.

Do you have a code snippet that performs the create and set values task in the way you prefer?

**Comment by jcoyne** [comment]
@elrayle This code sets all attributes and persists in a single write:
```ruby
Collection.create(attributes)
```

**Comment by jcoyne** [comment]
I'm not sure I see the point of this pull request. Why make a service that does exactly what the ActiveFedora API does?

**Comment by jcoyne** [comment]
I think this needs a rebase. It has commits on this branch that are in master.

**Comment by elrayle** [comment]
Discussions revealed that the current method for creating an instance of an ActiveFedora::Base subclass is via load_and_authorize_resource and using update_attributes to set metadata in the instance.  It does not appear that there is a need beyond creation and setting of attributes.  

Unless new requirements are identified, the consensus seems to be that CreateCollection is not needed.  I will close the PR, but not delete the branch until others have an opportunity to comment.

**Pull request closed without merging**
