### PR TITLE
Objects validations

### PR DESCRIPTION
**Pull request by terrellt**
I wanted some code to back up some of the things I said a couple days ago.

Currently we're using services instead of the public interface to add items, largely because we need a place to put dealing with the "don't put bad stuff in this accessor" use case. This is what it would look like to use the currently existing interface (#objects=), but just add validations so that it can't get into Fedora if it's not a proper PCDM configuration.

### CODE REVIEW

**Comment by terrellt** [comment]
I should note, with this I'm fairly certain things like AddObjectToCollection/AddCollectiontoCollection etc can go away, but I didn't want to go that far yet.

**Comment by jcoyne** [comment]
This would loading all the members on every save in order to validate they are all valid.  That seems like it would incur a significant performance penalty over just one validation when appending to the association. What you may want to do is figure a way to override Association#raise_on_type_mismatch (https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/associations/association.rb#L147-L152)

**Comment by terrellt** [comment]
@jcoyne +1. I'm not sure overriding is the way to go, but I'll see what I can do to make it an on-assignment check.

**Comment by mjgiarlo** [comment]
I was going to review this but it seems the PR is about to change a bit.  Ping me when it's ready, @terrellt .

**Comment by terrellt** [comment]
Closing until I change the tactic.

**Pull request closed without merging**
