### PR TITLE
Bump dependencies on AF and Af-agg

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by jcoyne** [comment]
Hold on this. Yanking AF 9.6.0

**Comment by mjgiarlo** [comment]
K, holding.

**Comment by jcoyne** [comment]
@mjgiarlo AF 9.6.1 is blocked by https://github.com/projecthydra/active_fedora/pull/938

**Comment by jcoyne** [comment]
AF 9.6.1 has been released so this is good to go.

**Pull request merged**
