### PR TITLE
Add related_files to Object.

### LINKED ISSUE #62: Objects can have related files

### PR DESCRIPTION
**Pull request by escowles**
* Rebasing #66 and expanding test coverage.  Fixes #62

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@terrellt posted this on #66:

> I thought the agreement in a previous call was to push off "related files" until after the sprint, and just deal with the "related objects (ore::aggregates)" concept.
> 
> Largely because of the concern that relating a "relatedFile" to an object isn't accurate, and it should rather just be linked directly to the file it's about.

Is that still a concern?

FWIW, **I** would like to see related files implemented so I can satisfy the FITS requirement without having to map 70+ technical metadata fields (in progress, though languishing).

**Comment by escowles** [comment]
I don't remember that, but @jcoyne did mention it.  I think I misunderstood him to mean it was out of scope for the May sprint.

IMHO, this is a pretty small piece of work and already done, so I'd vote to let it in.  Though I might be biased...

**Comment by jpstroop** [comment]
+1 to letting it in.

**Comment by terrellt** [comment]
:-1: Let me expand on my previous concerns a little bit.

This connects "related files" (like FITS metadata) directly to the PCDM object, and NOT to the bitstream that it's generated off of. This means there's no link between the PCDM::File and its "related files", when you delete the PCDM::File its FITS metadata is left around, and is making a statement that the PCDM::File and the related file are at the same level in the graph - a page has a thumbnail, an original, a medium resolution, and FITS metadata for...one of those, maybe.

I'd be :+1: if you could attach the related files to the bitstream (or its description container), but that requires https://jira.duraspace.org/browse/FCREPO-1526.

**Comment by terrellt** [comment]
I would also be closer to okay with this if it was at the Works level, and attached to the GenericFile, because that is "the file on disk"

**Comment by jpstroop** [comment]
Oh, thanks for the clarification @terrellt. /me changes vote to :-1:

**Comment by escowles** [comment]
@terrellt , but the PCDM docs don't say that.  They say that pcdm:Object should link to files with pcdm:hasRelatedFile for stuff that's related to the Object, but not a representation of it:

https://github.com/duraspace/pcdm/wiki#pcdmobject

I agree that linking the FITS back to the file it describes is a good thing to do, and having a container to manage the lifecycle so the FITS would be deleted automatically would be even better.  But I don't think the spec is requiring that.

**Comment by terrellt** [comment]
@escowles The spec for that was updated very quickly from a small forum thread despite some complaints similar to the ones I'm making now. The reason I wanted this pushed off is because I think the model is flawed for RelatedFiles, and there hasn't been a good venue or time to discuss that. I'm scared if we implement it here we're stuck with it.

**Comment by no-reply** [comment]
As an outsider to this sprint, I offer my (probably non-binding) :-1:. 

I agree with @terrellt's concerns, and agree that the process that introduced `pcdm:hasRelatedFile` was byzantine.  It happened across several threads, some of them private. Concerns that I raised were repeatedly ignored as the discussion moved to another thread.

**Comment by mjgiarlo** [comment]
Is it true that 1) this is a real need a bunch of us have, and 2) "correct" implementation in Fedora is intractable? In light of this, should we amend the PCDM spec? What's the path forward?

**Comment by terrellt** [comment]
@mjgiarlo :+1:

I'm going to spin up an email to hydra-tech tomorrow proposing this as an agenda item in the next hydra-tech call, with some background information, and we can disperse that appropriately to try to get all the interested parties together (both in Hydra and outside). Sound good?

**Comment by mjgiarlo** [comment]
You are not an outsider, @no-reply!  And there's no concept of binding vs. non-binding in Hydra, so thanks for sounding off.

**Comment by mjgiarlo** [comment]
:+1: @terrellt

**Comment by no-reply** [comment]
I think one or more "better" implementations were proposed that are manageable under Fedora 4 as-is.

I would be pretty okay with letting this in, as a feature, if it didn't seem so much like a continuation of the byzantine process mentioned above.

**Comment by mjgiarlo** [comment]
:ok: 

Hopefully a quorum of the interested parties above can make next week's Hydra Tech call so we can bat around those better implementation ideas.

**Comment by azaroth42** [comment]
Rewriting from hydra-tech list:

hasRelatedFile (or a subproperty) is the only practical way to connect two binary blobs at a structural level.  blob1 cannot make the assertion that it is described by blob2, and blob2 can't make the assertion that it describes blob1.  

So you need some other resource to assert the connection.  There are the following options:

* Reify the relationship into a pcdm:Object.  Advantage is that we don't have to change anything at all.  You have one hasFile, one hasRelatedFile. Problem (already) solved.  It would be easy to make a subClass of object to explicitly capture this use case's requirements.
* You include the relationship in the metadata resource about blob1 and/or blob2.  For fedora4, that's /fcr:metadata.  You can do that outside of PCDM in the comfort of whatever implementation needs it. And it seems outside of the scope of pcdm proper, as it's not _structural_ metadata.  There is still a requirement to distinguish files that constitute representations of the object, versus files that are associated with the object in other ways... so this wouldn't obviate the need for hasRelatedFile.

Perhaps I'm misunderstanding @no-reply, but the introduction of hasRelatedFile to the model was pretty transparent.  There was discussion at the Portland meetings, and feedback sought after them.  Do you mean introduction to the sprint work?

**Comment by terrellt** [comment]
@azaroth42 See list.

**Comment by no-reply** [comment]
> Perhaps I'm misunderstanding @no-reply, but the introduction of hasRelatedFile to the model was pretty transparent. There was discussion at the Portland meetings, and feedback sought after them. 

This is not true. The gap surrounding technical metadata files was raised the week after the most recent meetings in Portland in a private thread, including about 15 people, titled __Question about Fedora Works Application Profile (FWAP? seriously?)__. Several issues were discussed and alternatives proposed on that and other threads.

`hasRelatedFile` was introduced to the model documentation on the same day it was initially proposed, in this revision: https://wiki.duraspace.org/pages/diffpages.action?originalId=68062024&pageId=68062118

The current state of affairs was discussed as a workaround to [FCREPO-1526](https://jira.duraspace.org/browse/FCREPO-1526) in a `fedora-tech` thread titled __Fedora (?) Community Data Model__ that ran into March. I believe there were several other threads.

**Comment by escowles** [comment]
@no-reply -- it's true that the hasRelatedFile item was added to the wiki then, but it had been discussed long before that.  e.g., see https://github.com/projecthydra-labs/hydra-works/issues/9#issuecomment-58542023 from October.

**Comment by no-reply** [comment]
@escowles fair enough. My point is mainly that we left Portland in Feb. with a model in place. The next week an issue was raised in a private thread, the next day a solution was proposed and codified. Any time the issue has been raised since then, the answer has been to point to the document.

Call that "transparent" if you like; but as someone who has tried to contribute to this effort in good faith, I'm not convinced.

**Comment by escowles** [comment]
@no-reply I think there has been a real tension between wanting to be as inclusive as possible, while at the same time not wanting to seem like we are taking over the Hydra, Fedora, and/or Islandora communities.  You're right that there have been a couple of big private threads at various points when it seemed like there was stuff to talk about, but for whatever reason, some people didn't feel comfortable in whatever public forums.  I definitely think it's important to get more buy-in in a public forum before moving forward with things, and I should have done that with hasRelatedFile.

I'm hesitant to setup yet-another-mailing-list-and-wiki-and-phone-call, because who has time for that.  But at the same time, I feel like we're going to continue having problems like this if we don't.

**Comment by mjgiarlo** [comment]
This doesn't touch on the larger issues raised here, but I thought I'd explain why I sent the private message about technical metadata in February. To quote the first paragraph of said message:

>This message grew out of a question I posed to #projecthydra earlier today.  I originally planned to take this to hydra-tech, but I decided to run it by the lot of you instead because we have not yet widely announced the latest batch of changes to the "works" data model, so this might confuse folks.

So, no, this was not transparent. Point taken! Given that PCDM was still without an agreed-upon name, and was mired in multiple megathreads, and few outside those 15 people knew what it was, I thought it reasonable to ping that group about a gap in my own knowledge about a brand-new, rapidly changing, complex thing. If that helped create a pattern of exclusivity, I'm truly sorry; that was not my intent.

**Comment by no-reply** [comment]
Thanks @escowles & @mjgiarlo.

I should be clear that my point isn't to blame individuals. While I admit to being frustrated about this, I don't think anyone in particular was responsible for ushering the issue into a public discussion. People were---and are---trying to carry work forward; my point is also not to disrupt that.

I'm going away (to Disneyland! :scream_cat:) for a long weekend, so I'll let others have their say. I *do* hope, whatever happens in this PR, we will follow through with the planned discussion in next week's Tech call.

**Comment by mjgiarlo** [comment]
OBEY THE :mouse: @no-reply

**Comment by jcoyne** [comment]
Won't fix see #184

**Pull request closed without merging**
